 
#
# This LookML file was generated by AtScale on 2023-07-11T08:45:01.878818Z
#
# AtScale engine version: 2023.1.0.11998
# AtScale DesignCenter version: 2023.1.0.20596
# AtScale version: 2023.1.0.5750
# Organization: default
# Project: BigQuery Project

connection: "atscale_test"
label: "BigQuery Project"


include: "/views/BigQuery_Project/CubeAndReport.view.lkml"


explore: CubeAndReport {
  label: "CubeAndReport"
}

