 
#
# This LookML file was generated by AtScale on 2023-07-11T08:15:21.477414Z
#
# AtScale engine version: 2023.1.0.11998
# AtScale DesignCenter version: 2023.1.0.20596
# AtScale version: 2023.1.0.5750
# Organization: default
# Project: DAC

connection: "atscale_google_partner_instance"
label: "DAC"


include: "/views/DAC/DAC.view.lkml"


explore: DAC {
  label: "DAC"
}

